root = "."
tmp_dir = "build"

[build]
  cmd = "go build -o ./build/main ./cmd/server/main.go"
  bin = "./build/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "build"]
  include_dir = ["cmd", "config", "init", "internal", "internal/server/handler", "internal/model", "migrations"]
  exclude_file = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
